version: '3.8'

services:
  bugzilla:
    build: .
    ports:
      - "80:80"
    environment:
      BUGZILLA_DB_HOST: db
      BUGZILLA_DB_NAME: bugzilla
      BUGZILLA_DB_USER: bugzilla
      BUGZILLA_DB_PASS: mysecretpassword
      BUGZILLA_ADMIN_EMAIL: admin@example.com
      BUGZILLA_ADMIN_PASS: anothersecretpassword
      BUGZILLA_ADMIN_REALNAME: "Admin User"
      SERVERNAME: "http://localhost"
      SERVERADMIN_EMAIL: "webmaster@example.com"
      POSTFIX_HOSTNAME: "example.com"
      POSTFIX_NETWORKS: "172.0.0.0/8 192.168.0.0/16"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bugzilla
      MYSQL_USER: bugzilla
      MYSQL_PASSWORD: mysecretpassword
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
